const assert = require('node:assert/strict')
const fs = require('node:fs')

const rombel = fs.readFileSync('src/pages/admin/RombelPage.tsx', 'utf8')
const jurnal = fs.readFileSync('src/pages/admin/JurnalPage.tsx', 'utf8')
const server = fs.readFileSync('server/index.cjs', 'utf8')

assert.match(rombel, /createPortal/, 'detail rombel harus portaled')
assert.match(rombel, /grid-cols-1 sm:grid-cols-2 md:grid-cols-3/, 'tile rombel harus 1\/2\/3 kolom')
assert.match(rombel, /role="button"/)
assert.match(rombel, /onKeyDown=/, 'tile rombel harus bisa dibuka lewat keyboard')
assert.match(rombel, /\/rombel\/.*\/siswa/, 'siswa harus dimuat lazy saat detail dibuka')
assert.match(server, /app\.get\('\/api\/rombel\/:id\/siswa'/)
assert.match(server, /r\.tenant_id = \? AND s\.tenant_id = \?/, 'endpoint harus validasi tenant rombel dan siswa')
assert.match(jurnal, /grid-cols-1 sm:grid-cols-2 md:grid-cols-3/, 'tile jurnal harus 1\/2\/3 kolom')
assert.doesNotMatch(jurnal, /ResponsiveTable/, 'jurnal harus tile nyata')
assert.match(server, /strftime\('%w', j\.tanggal\)/, 'resolusi jadwal harus mengikuti hari jurnal')
assert.match(server, /COALESCE\(jg\.nama, g\.nama\) as guru_nama/, 'guru harus diresolusi dari relasi jadwal kanonik')
console.log('rombel jurnal tile tests passed')
