const fs = require('node:fs')
const path = require('node:path')
const crypto = require('node:crypto')
const Database = require('better-sqlite3')

class ValidationError extends Error {}
const S=(label,tables,optional=[])=>({label,tables,optional})
const SECTIONS=Object.freeze({
 settings:S('Pengaturan Lembaga',['settings']), notif:S('Pengaturan Notifikasi',['notif_settings']),
 gtk:S('Data GTK',['gtk']), mapel:S('Mata Pelajaran',['mapel']), tahun_ajaran:S('Tahun Ajaran',['tahun_ajaran']), rombel:S('Rombongan Belajar',['rombel']), siswa:S('Data Siswa',['siswa']),
 jadwal:S('Jadwal & Pengajar',['template_jadwal','pengajar','jadwal']),
 jurnal:S('Jurnal & Nilai',['jurnal_mengajar','penilaian_harian','rapor','catatan_kepribadian','rapor_sync_log'],['rapor_sync_log']),
 absensi:S('Absensi',['absensi_siswa','absensi_guru','kegiatan_khusus','absensi_kegiatan']),
 ekskul:S('Ekstrakurikuler',['ekskul','ekskul_anggota','absensi_ekskul']), tagihan:S('Tagihan',['jenis_tagihan','tagihan']),
 tabungan:S('Tabungan',['tabungan']), cashless:S('Cashless',['cashless_accounts','cashless_transactions']),
 kalender:S('Kalender KBM',['kalender_kbm']), modul:S('Modul Ajar',['modul_ajar']),
 keuangan:S('Keuangan',['keuangan_akun','keuangan_kategori','keuangan_transaksi']),
 tahfidz:S('Tahfidz',['tahfidz_kelompok','tahfidz_peserta','tahfidz_pertemuan','tahfidz_absensi']),
 pesantren:S('Pesantren',['rombel_jam_pulang']), perpustakaan:S('Perpustakaan',['library_config'])
})
const EXCLUDED=Object.freeze({users:'password dan akun',wa_gateway_config:'token, API key, dan sesi WhatsApp',broadcast_log:'log operasional',broadcast_detail:'nomor penerima dan log operasional'})
const MAX_ROWS=100000, MAX_BYTES=10*1024*1024, DENY=/(password|passwd|secret|token|api[_-]?key|session|credential|private[_-]?key)/i
const canonical=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?`[${v.map(canonical).join(',')}]`:`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`
const checksum=v=>crypto.createHash('sha256').update(canonical(v)).digest('hex')
const q=x=>'"'+String(x).replaceAll('"','""')+'"'
function createService(db,options={}) {
 const backupDir=options.backupDir||process.env.JURNALKU_BACKUP_DIR||path.resolve(__dirname,'../var/backups')
 const names=new Set(db.prepare("SELECT name FROM sqlite_master WHERE type='table'").all().map(x=>x.name))
 const info=t=>db.pragma(`table_info(${JSON.stringify(t)})`), cols=t=>info(t).map(x=>x.name), tenantTable=t=>names.has(t)&&cols(t).includes('tenant_id')
 const available=k=>{const s=SECTIONS[k];return !!s&&s.tables.filter(t=>!s.optional.includes(t)).every(tenantTable)&&s.tables.some(tenantTable)}
 const selectedKeys=input=>{const list=input===undefined?Object.keys(SECTIONS).filter(available):input;if(!Array.isArray(list)||!list.length||list.some(k=>typeof k!=='string'||!available(k))||new Set(list).size!==list.length)throw new ValidationError('Bagian backup kosong, duplikat, atau tidak didukung');return list}
 const safeCols=t=>cols(t).filter(c=>c==='tenant_id'||!DENY.test(c))
 const rowsFor=(key,tid)=>SECTIONS[key].tables.filter(tenantTable).flatMap(t=>db.prepare(`SELECT ${safeCols(t).map(q)} FROM ${q(t)} WHERE tenant_id=?`).all(tid).map(r=>({__table:t,...r})))
 function exportData(tid,selected){if(!tid)throw new ValidationError('Tenant wajib');const tenant=db.prepare('SELECT id,nama FROM tenants WHERE id=?').get(tid);if(!tenant)throw new ValidationError('Tenant tidak ditemukan');const tables={},sections=[];for(const key of selectedKeys(selected)){tables[key]=rowsFor(key,tid);sections.push({key,count:tables[key].length,checksum:checksum(tables[key])})}return{manifest:{format:'jurnalku-tenant-backup',schema_version:1,created_at:new Date().toISOString(),tenant,users_excluded:true,excluded:EXCLUDED,sections},tables}}
 function normalized(tid,artifact){if(!artifact||Buffer.byteLength(JSON.stringify(artifact))>MAX_BYTES||artifact.manifest?.format!=='jurnalku-tenant-backup'||artifact.manifest.schema_version!==1)throw new ValidationError('Format atau versi backup tidak valid');if(artifact.manifest.tenant?.id!==tid)throw new ValidationError('Backup lintas tenant ditolak');const sections=artifact.manifest.sections;if(!Array.isArray(sections)||!sections.length||new Set(sections.map(s=>s.key)).size!==sections.length||Object.keys(artifact.tables||{}).sort().join()!==sections.map(s=>s.key).sort().join())throw new ValidationError('Bagian backup kosong, duplikat, atau tidak cocok');let total=0;const rows=[];for(const s of sections){if(!available(s.key)||Object.keys(s).filter(k=>k!=='label').sort().join()!=='checksum,count,key'||!Array.isArray(artifact.tables[s.key])||s.count!==artifact.tables[s.key].length||checksum(artifact.tables[s.key])!==s.checksum)throw new ValidationError('Manifest, jumlah, atau checksum tidak cocok');for(const row of artifact.tables[s.key]){const t=row?.__table;if(!t||!SECTIONS[s.key].tables.includes(t)||!tenantTable(t))throw new ValidationError('Tabel tidak diizinkan');const expected=new Set(['__table',...safeCols(t)]);if(Object.keys(row).some(c=>!expected.has(c))||safeCols(t).some(c=>!(c in row)))throw new ValidationError('Bentuk baris tidak valid');rows.push({...row,tenant_id:tid})}total+=artifact.tables[s.key].length}if(total>MAX_ROWS)throw new ValidationError('Jumlah baris melewati batas');return{sections,rows,total}}
 function graph(rows){const tables=[...new Set(rows.map(r=>r.__table))],set=new Set(tables),edges=[];for(const child of tables)for(const fk of db.pragma(`foreign_key_list(${JSON.stringify(child)})`))if(set.has(fk.table))edges.push([fk.table,child]);const out=[],left=new Set(tables);while(left.size){const t=[...left].find(x=>!edges.some(([p,c])=>c===x&&left.has(p)));if(!t)throw new ValidationError('Siklus dependency tidak didukung');out.push(t);left.delete(t)}return out}
 function validateRefs(tid,rows){const incoming=new Map;for(const r of rows){if(!incoming.has(r.__table))incoming.set(r.__table,[]);incoming.get(r.__table).push(r)}for(const r of rows)for(const fk of db.pragma(`foreign_key_list(${JSON.stringify(r.__table)})`)){const value=r[fk.from];if(value==null)continue;if(!tenantTable(fk.table))throw new ValidationError(`FK ${r.__table}.${fk.from} menuju tabel global tidak didukung`);const inFile=(incoming.get(fk.table)||[]).some(x=>x[fk.to]===value&&x.tenant_id===tid);const inDb=db.prepare(`SELECT 1 FROM ${q(fk.table)} WHERE ${q(fk.to)}=? AND tenant_id=?`).get(value,tid);if(!inFile&&!inDb)throw new ValidationError(`FK lintas tenant atau hilang: ${r.__table}.${fk.from}`)}}
 function snapshot(tid){fs.mkdirSync(backupDir,{recursive:true,mode:0o700});fs.chmodSync(backupDir,0o700);const target=path.join(backupDir,`${Date.now()}-${crypto.randomBytes(8).toString('hex')}-${String(tid).replace(/[^a-z0-9_-]/gi,'_')}.sqlite`);db.exec(`VACUUM INTO '${target.replaceAll("'","''")}'`);fs.chmodSync(target,0o600);const check=new Database(target,{readonly:true,fileMustExist:true});try{if(check.pragma('quick_check',{simple:true})!=='ok')throw new Error('Snapshot SQLite rusak')}finally{check.close()}for(const f of fs.readdirSync(backupDir).filter(x=>x.endsWith('.sqlite')).sort((a,b)=>fs.statSync(path.join(backupDir,a)).mtimeMs-fs.statSync(path.join(backupDir,b)).mtimeMs).slice(0,-20))fs.unlinkSync(path.join(backupDir,f));return target}
 function restore(tid,artifact,mode='merge',confirmation,replaceConfirmation){const data=normalized(tid,artifact);if(confirmation!=='RESTORE'||!['merge','replace'].includes(mode)||mode==='replace'&&replaceConfirmation!=='REPLACE DATA')throw new ValidationError('Konfirmasi restore tidak valid');validateRefs(tid,data.rows);const order=graph(data.rows),byTable=Object.groupBy(data.rows,r=>r.__table);snapshot(tid);const counts={inserted:0,skipped:0};db.transaction(()=>{if(mode==='replace'){const chosen=new Set(order);for(const parent of order)for(const fkRow of db.prepare("SELECT name FROM sqlite_master WHERE type='table'").all())if(tenantTable(fkRow.name)&&!chosen.has(fkRow.name))for(const fk of db.pragma(`foreign_key_list(${JSON.stringify(fkRow.name)})`))if(fk.table===parent&&db.prepare(`SELECT 1 FROM ${q(fkRow.name)} WHERE tenant_id=? LIMIT 1`).get(tid))throw new ValidationError(`Replace ditolak: dependency ${fkRow.name} tidak dipilih`);for(const t of [...order].reverse())db.prepare(`DELETE FROM ${q(t)} WHERE tenant_id=?`).run(tid)}for(const t of order)for(const row of byTable[t]||[]){const pk=info(t).filter(c=>c.pk).sort((a,b)=>a.pk-b.pk);if(mode==='merge'&&pk.length){const where=pk.map(c=>`${q(c.name)}=?`).join(' AND '),hit=db.prepare(`SELECT tenant_id FROM ${q(t)} WHERE ${where}`).get(...pk.map(c=>row[c.name]));if(hit){if(hit.tenant_id!==tid)throw new ValidationError(`Konflik ID lintas tenant pada ${t}`);counts.skipped++;continue}}const cs=safeCols(t);db.prepare(`INSERT INTO ${q(t)} (${cs.map(q)}) VALUES (${cs.map(c=>'@'+c)})`).run(row);counts.inserted++}const bad=db.pragma('foreign_key_check');if(bad.length)throw new ValidationError('foreign_key_check gagal')})();return{success:true,...counts}}
 function preview(tid,a){const d=normalized(tid,a);validateRefs(tid,d.rows);return{valid:true,total:d.total,sections:d.sections.map(s=>({key:s.key,label:SECTIONS[s.key].label,count:s.count}))}}
 return{exportData,preview,restore,checksum,sections:tid=>Object.entries(SECTIONS).filter(([k])=>available(k)).map(([key,v])=>({key,label:v.label,count:rowsFor(key,tid).length})),excluded:EXCLUDED}
}
function registerRoutes(app,db,{ADMIN,upload,dbPath}){const service=createService(db,{dbPath}),wrap=fn=>(req,res,next)=>{Promise.resolve().then(()=>fn(req,res)).catch(next)},up=(req,res,next)=>upload.single('backup')(req,res,e=>e?next(new ValidationError(e.code==='LIMIT_FILE_SIZE'?'File terlalu besar':e.message)):next()),parse=req=>{if(!req.file)throw new ValidationError('File backup wajib');try{return JSON.parse(req.file.buffer.toString('utf8'))}catch{throw new ValidationError('JSON backup tidak valid')}};app.get('/api/backup-restore/sections',ADMIN,wrap((req,res)=>res.json(service.sections(req.tenantId))));app.post('/api/backup-restore/export',ADMIN,wrap((req,res)=>res.set({'Content-Type':'application/json','Content-Disposition':`attachment; filename="jurnalku-${Date.now()}.json"`}).send(JSON.stringify(service.exportData(req.tenantId,req.body.sections)))));app.post('/api/backup-restore/preview',ADMIN,up,wrap((req,res)=>res.json(service.preview(req.tenantId,parse(req)))));app.post('/api/backup-restore/restore',ADMIN,up,wrap((req,res)=>res.json(service.restore(req.tenantId,parse(req),req.body.mode,req.body.confirmation,req.body.replace_confirmation))));app.use('/api/backup-restore',(e,req,res,next)=>res.status(e instanceof ValidationError?400:500).json({error:e.message||'Backup/restore gagal'}))}
module.exports={createService,registerRoutes,SECTIONS,EXCLUDED,ValidationError}
