const ExcelJS=require('exceljs'),crypto=require('node:crypto')
const HEADERS={Tagihan:['id','nis','jenis_tagihan','bulan','tahun','nominal','status','tanggal_bayar','metode_bayar','keterangan'],Tabungan:['id','nis','tanggal','tipe','nominal','keterangan'],Cashless:['id','nis','tanggal','jenis','nominal','referensi'],Keuangan:['id','tanggal','akun','kategori','tipe','nominal','keterangan']}
const QUERIES={Tagihan:`SELECT t.id,s.nis,j.nama jenis_tagihan,t.bulan,t.tahun,t.nominal,t.status,t.tanggal_bayar,t.metode_bayar,t.keterangan FROM tagihan t JOIN siswa s ON s.id=t.siswa_id AND s.tenant_id=t.tenant_id JOIN jenis_tagihan j ON j.id=t.jenis_tagihan_id AND j.tenant_id=t.tenant_id WHERE t.tenant_id=? ORDER BY t.created_at`,Tabungan:`SELECT t.id,s.nis,t.tanggal,t.tipe,t.nominal,t.keterangan FROM tabungan t JOIN siswa s ON s.id=t.siswa_id AND s.tenant_id=t.tenant_id WHERE t.tenant_id=? ORDER BY t.created_at`,Cashless:`SELECT l.id,s.nis,l.created_at tanggal,l.kind jenis,ABS(l.amount) nominal,l.reference referensi FROM cashless_ledger l JOIN siswa s ON s.id=l.student_id AND s.tenant_id=l.tenant_id WHERE l.tenant_id=? ORDER BY l.created_at`,Keuangan:`SELECT t.id,t.tanggal,a.nama akun,k.nama kategori,t.tipe,t.nominal,t.keterangan FROM keuangan_transaksi t JOIN keuangan_akun a ON a.id=t.akun_id AND a.tenant_id=t.tenant_id JOIN keuangan_kategori k ON k.id=t.kategori_id AND k.tenant_id=t.tenant_id WHERE t.tenant_id=? ORDER BY t.tanggal,t.created_at`}
async function exportFinance(db,tenant){const wb=new ExcelJS.Workbook();for(const name of Object.keys(HEADERS)){const sh=wb.addWorksheet(name);sh.addRow(HEADERS[name]);for(const row of db.prepare(QUERIES[name]).all(tenant))sh.addRow(HEADERS[name].map(k=>row[k]??''));sh.getRow(1).font={bold:true};sh.views=[{state:'frozen',ySplit:1}];sh.columns.forEach(c=>c.width=18)}return Buffer.from(await wb.xlsx.writeBuffer())}
const text=v=>String(v??'').trim(),amount=v=>Number(v)
async function previewFinance(db,tenant,buffer){const wb=new ExcelJS.Workbook();await wb.xlsx.load(await buffer);const rows=[],errors=[];let count=0
 if(!wb.worksheets.length)throw Error('Workbook kosong');for(const sh of wb.worksheets){if(!HEADERS[sh.name]){errors.push({sheet:sh.name,row:1,error:'Sheet tidak didukung'});continue}const headers=sh.getRow(1).values.slice(1).map(text);if(headers.join('|')!==HEADERS[sh.name].join('|')){errors.push({sheet:sh.name,row:1,error:'Header tidak cocok'});continue}sh.eachRow((r,n)=>{if(n===1)return;if(++count>5000)return;const data=Object.fromEntries(headers.map((h,i)=>[h,r.getCell(i+1).value]));try{rows.push(validate(db,tenant,sh.name,data,n))}catch(e){errors.push({sheet:sh.name,row:n,error:e.message})}})}if(count>5000)throw Error('Maksimal 5000 baris');const ids=new Set();for(const r of rows)if(ids.has(r.id))errors.push({sheet:r.sheet,row:r.row,error:'Duplikat id dalam workbook'});else ids.add(r.id);return{valid:rows.length,errors,rows,committable:errors.length===0}}
function ref(db,table,field,value,tenant,extra=''){const row=db.prepare(`SELECT id FROM ${table} WHERE ${field}=? AND tenant_id=? ${extra}`).get(text(value),tenant);if(!row)throw Error(`${field} tidak ditemukan`);return row.id}
function validate(db,t,s,r,n){for(const v of Object.values(r))if(v&&typeof v==='object'&&!(v instanceof Date))throw Error('Formula/object tidak didukung');const id=text(r.id);if(!id)throw Error('id wajib');const nominal=amount(r.nominal);if(!Number.isSafeInteger(nominal)||nominal<=0)throw Error('nominal wajib integer positif');const date=v=>{const x=v instanceof Date?v.toISOString().slice(0,10):text(v);if(!/^\d{4}-\d{2}-\d{2}$/.test(x)||Number.isNaN(Date.parse(x+'T00:00:00Z')))throw Error('tanggal tidak valid');return x},base={sheet:s,row:n,id,nominal}
 if(s==='Tagihan'){const bulan=text(r.bulan),tahun=text(r.tahun),status=text(r.status);if(!/^(0?[1-9]|1[0-2]|Januari|Februari|Maret|April|Mei|Juni|Juli|Agustus|September|Oktober|November|Desember)$/.test(bulan))throw Error('bulan tidak valid');if(!/^\d{4}$/.test(tahun))throw Error('tahun tidak valid');if(!['belum_bayar','lunas'].includes(status))throw Error('status tidak valid');return{...base,siswa_id:ref(db,'siswa','nis',r.nis,t),jenis_id:ref(db,'jenis_tagihan','nama',r.jenis_tagihan,t),bulan,tahun,status,tanggal_bayar:r.tanggal_bayar?date(r.tanggal_bayar):null,metode:text(r.metode_bayar),keterangan:text(r.keterangan)}}
 if(s==='Tabungan'){if(!['setor','tarik'].includes(text(r.tipe)))throw Error('tipe tidak valid');return{...base,siswa_id:ref(db,'siswa','nis',r.nis,t),tanggal:date(r.tanggal),tipe:text(r.tipe),keterangan:text(r.keterangan)}}
 if(s==='Cashless'){if(!['credit','debit'].includes(text(r.jenis)))throw Error('jenis tidak valid');return{...base,siswa_id:ref(db,'siswa','nis',r.nis,t),tanggal:date(r.tanggal),jenis:text(r.jenis),referensi:text(r.referensi)}}
 const tipe=text(r.tipe);if(!['masuk','keluar'].includes(tipe))throw Error('tipe tidak valid');const kategori=db.prepare('SELECT id FROM keuangan_kategori WHERE nama=? AND tenant_id=? AND tipe=?').get(text(r.kategori),t,tipe);if(!kategori)throw Error('kategori tidak ditemukan');return{...base,tanggal:date(r.tanggal),akun_id:ref(db,'keuangan_akun','nama',r.akun,t),kategori_id:kategori.id,tipe,keterangan:text(r.keterangan)}}
function commitFinance(db,tenant,actor,rows,policy,errors=[]){if(errors.length)throw Error('Preview mengandung error');if(!['skip','reject'].includes(policy))throw Error('Kebijakan duplikat wajib skip atau reject');return db.transaction(()=>{let inserted=0,skipped=0;for(const r of rows){const table={Tagihan:'tagihan',Tabungan:'tabungan',Cashless:'cashless_ledger',Keuangan:'keuangan_transaksi'}[r.sheet];if(db.prepare(`SELECT 1 FROM ${table} WHERE id=?`).get(r.id)){if(policy==='reject')throw Error(`Duplikat id ${r.id}`);skipped++;continue}
 if(r.sheet==='Tagihan')db.prepare('INSERT INTO tagihan(id,siswa_id,jenis_tagihan_id,bulan,tahun,nominal,status,tanggal_bayar,metode_bayar,keterangan,tenant_id) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(r.id,r.siswa_id,r.jenis_id,r.bulan,r.tahun,r.nominal,r.status,r.tanggal_bayar,r.metode,r.keterangan,tenant)
 else if(r.sheet==='Tabungan'){const last=db.prepare('SELECT saldo_akhir FROM tabungan WHERE siswa_id=? AND tenant_id=? ORDER BY created_at DESC LIMIT 1').get(r.siswa_id,tenant)?.saldo_akhir||0,next=last+(r.tipe==='setor'?r.nominal:-r.nominal);if(next<0)throw Error(`Saldo tidak cukup baris ${r.row}`);db.prepare('INSERT INTO tabungan(id,siswa_id,tanggal,tipe,nominal,saldo_akhir,keterangan,tenant_id) VALUES(?,?,?,?,?,?,?,?)').run(r.id,r.siswa_id,r.tanggal,r.tipe,r.nominal,next,r.keterangan,tenant)}
 else if(r.sheet==='Cashless')db.prepare('INSERT INTO cashless_ledger(id,tenant_id,student_id,amount,kind,idempotency_key,actor_id,reference,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(r.id,tenant,r.siswa_id,r.jenis==='debit'?-r.nominal:r.nominal,r.jenis,'excel:'+r.id,actor,r.referensi,r.tanggal||new Date().toISOString())
 else db.prepare('INSERT INTO keuangan_transaksi(id,tanggal,akun_id,kategori_id,tipe,nominal,keterangan,bukti,tenant_id) VALUES(?,?,?,?,?,?,?,?,?)').run(r.id,r.tanggal,r.akun_id,r.kategori_id,r.tipe,r.nominal,r.keterangan,'',tenant);inserted++}return{inserted,skipped}})()}
function registerFinanceExcelRoutes(app,db,{authorize,upload}){const previews=new Map();app.get('/api/finance-excel/export',authorize,async(r,s)=>{const b=await exportFinance(db,r.tenantId);s.set({'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':'attachment; filename="bendahara.xlsx"'}).send(b)});app.post('/api/finance-excel/preview',authorize,upload.single('file'),async(r,s)=>{try{if(!r.file)return s.status(400).json({error:'File wajib'});const p=await previewFinance(db,r.tenantId,r.file.buffer),token=p.committable?crypto.randomUUID():null;if(token)previews.set(token,{tenant:r.tenantId,rows:p.rows,expires:Date.now()+600000});s.json({token,valid:p.valid,errors:p.errors,rows:p.rows.slice(0,20).map(({sheet,row,id})=>({sheet,row,id}))})}catch(e){s.status(400).json({error:e.message})}});app.post('/api/finance-excel/commit',authorize,(r,s)=>{try{const p=previews.get(r.body.token);if(!p||p.tenant!==r.tenantId||p.expires<Date.now())return s.status(400).json({error:'Preview kedaluwarsa'});previews.delete(r.body.token);const out=commitFinance(db,r.tenantId,r.user.id,p.rows,r.body.duplicate_policy);s.json(out)}catch(e){s.status(400).json({error:e.message})}})}
module.exports={exportFinance,previewFinance,commitFinance,registerFinanceExcelRoutes}
