import { useEffect, useState } from 'react'
import { Loader2, Upload, Send } from 'lucide-react'
import toast from 'react-hot-toast'
import api from '../../services/api'

type Qris = { enabled: boolean; shopee_qris: string; gopay_qris: string; providers: string[] }
const empty: Qris = { enabled: false, shopee_qris: '', gopay_qris: '', providers: [] }
const imageData = (file: File, set: (x: string) => void) => { if (!['image/png','image/jpeg','image/webp'].includes(file.type) || file.size > 1024 * 1024) return toast.error('Upload gambar PNG/JPG/WEBP maksimal 1 MB'); const r = new FileReader(); r.onload = () => set(String(r.result || '')); r.readAsDataURL(file) }
export default function SiswaQrisTopupPage() {
  const [qris, setQris] = useState(empty); const [studentId, setStudentId] = useState(''); const [children, setChildren] = useState<any[]>([]); const [provider, setProvider] = useState(''); const [amount, setAmount] = useState(''); const [uniqueCode, setUniqueCode] = useState(() => String(Math.floor(100 + Math.random() * 900))); const [name, setName] = useState(''); const [sender, setSender] = useState(''); const [proof, setProof] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { Promise.all([api.get('/cashless/provider/bank_transfer/static-qris'), api.get('/portal/children')]).then(([q, c]) => { setQris(q.data); setChildren(c.data); if (c.data.length === 1) setStudentId(c.data[0].id); setProvider(q.data.providers[0] || '') }).catch(() => toast.error('Gagal memuat QRIS')) }, [])
  const baseAmount = Number(amount) || 0; const transferAmount = baseAmount + (Number(uniqueCode) || 0)
  const submit = async () => { setSaving(true); try { await api.post('/cashless/topup/manual', { student_id: studentId, provider, amount: baseAmount, unique_code: uniqueCode, transfer_amount: transferAmount, atas_nama: name, no_rek_dari: sender, bukti_transfer: proof }); toast.success('Laporan transfer dikirim, menunggu verifikasi bendahara'); setAmount(''); setUniqueCode(String(Math.floor(100 + Math.random() * 900))); setName(''); setSender(''); setProof('') } catch (e: any) { toast.error(e.response?.data?.error || 'Gagal mengirim laporan') } finally { setSaving(false) } }
  const img = provider === 'shopee' ? qris.shopee_qris : qris.gopay_qris
  return <div className="space-y-5 max-w-3xl"><div><h1 className="text-2xl font-bold">Top-up QRIS</h1><p className="text-sm text-gray-500 mt-1">Scan QRIS merchant, lalu laporkan detail transfer agar bendahara dapat mencocokkannya.</p></div>{!qris.enabled || !qris.providers.length ? <div className="rounded-xl bg-amber-50 p-4 text-amber-800">QRIS belum diaktifkan oleh lembaga.</div> : <><div className="flex gap-2">{qris.providers.map(p => <button key={p} onClick={() => setProvider(p)} className={`px-4 py-2 rounded-lg ${provider === p ? 'bg-primary text-white' : 'bg-gray-100'}`}>{p === 'shopee' ? 'ShopeePay' : 'GoPay'}</button>)}</div><div className="bg-white rounded-xl border p-4 text-center"><img src={img} alt="QRIS merchant" className="w-72 h-72 object-contain mx-auto" /><p className="text-sm font-semibold mt-2">{provider === 'shopee' ? 'ShopeePay Merchant' : 'GoPay Merchant'}</p></div><div className="bg-white rounded-xl border p-5 space-y-3"><select value={studentId} onChange={e => setStudentId(e.target.value)} className="w-full border rounded-lg p-2"><option value="">Pilih siswa</option>{children.map(c => <option key={c.id} value={c.id}>{c.nama} ({c.nis})</option>)}</select><input type="number" placeholder="Nominal top-up (contoh 50000)" value={amount} onChange={e => setAmount(e.target.value)} className="w-full border rounded-lg p-2" /><div className="rounded-lg bg-blue-50 border border-blue-200 p-3 text-sm text-blue-800">Kode unik verifikasi: <strong>{uniqueCode || '---'}</strong><br />Transfer tepat <strong>Rp {transferAmount.toLocaleString('id-ID')}</strong> (nominal top-up + kode unik 3 digit).</div><input placeholder="Nama pengirim sesuai aplikasi" value={name} onChange={e => setName(e.target.value)} className="w-full border rounded-lg p-2" /><input placeholder="Nomor HP/akun pengirim" value={sender} onChange={e => setSender(e.target.value)} className="w-full border rounded-lg p-2" /><label className="block text-sm">Bukti transfer (wajib)<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e => e.target.files?.[0] && imageData(e.target.files[0], setProof)} className="block mt-1" /></label>{proof && <img src={proof} alt="Bukti transfer" className="max-h-52 rounded border" />}<button onClick={submit} disabled={saving} className="w-full bg-primary text-white rounded-lg py-2.5 flex justify-center gap-2">{saving ? <Loader2 className="animate-spin" size={17} /> : <Send size={17} />} Kirim Laporan Transfer</button></div></>}</div>
}
